import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ethers } from "ethers";
import { BaseProvider } from "@ethersproject/providers";
import { GetServerSideProps } from 'next'


const network = "kovan";
const alchemyToken = process.env.ALCHEMY_KOVAN_TOKEN;

const provider: BaseProvider = ethers.getDefaultProvider(network, {
  alchemy: alchemyToken,
});

interface HomeProps {
  blockNumber: string
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const blockNumber = await provider.getBlockNumber();
  return {
    props: {
      blockNumber,
    },
  }
}

const Home: NextPage<HomeProps> = (props: HomeProps) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            {props.blockNumber}
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
